# Type Name ID GECOS Home Shell
g syntrop - -
u syntrop-runtime - "Syntropd Runtime Daemon" /var/lib/models /usr/bin/nologin
m syntrop-runtime syntrop
m syntrop-runtime video
m syntrop-runtime render
