[package]
name = "runtimed-daemon"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
qa-test-helpers = []

[lib]
path = "src/lib.rs"

[[bin]]
name = "runtimed"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
libc.workspace = true
rustix.workspace = true
runtimed-core = { path = "../runtimed-core" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true